using pb0 = Pin<'B', 0>; // ICP1, general I/O
using pb1 = Pin<'B', 1>; // OC1A, general I/O
using pb2 = Pin<'B', 2>; // OC1B, !SS, general I/O
using pb3 = Pin<'B', 3>; // MOSI, OC2, general I/O
using pb4 = Pin<'B', 4>; // MISO, general I/O
using pb5 = Pin<'B', 5>; // SCK, general I/O
using pb6 = Pin<'B', 6>; // XTAL1, TOSCI1
using pb7 = Pin<'B', 7>; // XTAL2, TOSCI2
using pc0 = Pin<'C', 0>; // ADC0
using pc1 = Pin<'C', 1>; // ADC1
using pc2 = Pin<'C', 2>; // ADC2
using pc3 = Pin<'C', 3>; // ADC3
using pc4 = Pin<'C', 4>; // ADC4, SDA
using pc5 = Pin<'C', 5>; // ADC5, SCL
using pc6 = Pin<'C', 6>; // RESET, GPIO only if fuse disabled
using pd0 = Pin<'D', 0>; // RXD
using pd1 = Pin<'D', 1>; // TXD
using pd2 = Pin<'D', 2>; // INT0
using pd3 = Pin<'D', 3>; // INT1
using pd4 = Pin<'D', 4>; // XCK, T0
using pd5 = Pin<'D', 5>; // T1, OC0B
using pd6 = Pin<'D', 6>; // AIN0, OC0A
using pd7 = Pin<'D', 7>; // AIN1